language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
# command to install dependencies
before_install:
#  - apt-cache search root|grep -i ^root
  - sudo apt-get install root-system
install:
  - pip install .
# command to run tests
script:
  - pytest -k "not root and not fluka"
