language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
# command to install dependencies
before_install:
  - sudo apt-get install root-system
  - which root
  - echo $ROOTSYS
  - dpkg -L root-system root-system-bin root-system-common libroot-core5.34 libroot-core-dev
  - root-config --features
install:
  - pip install .
# command to run tests
script:
  - pytest -k "not fluka"
